# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a879f11b3ecdb38d274bf266a819c6e99b1d4ca93735d35faaf91503e4beb06f5007fae89375fe6535c2a9f5c1fb71a458a5f1c758f8839fc6fc5e9178c3e780

test:
  secret_key_base: 35b29afba73d2d5092ad62dfbc34bca6e8a27bdc3eb35f7848503e42df9aef8f4a96d62b7a95fcb28ec671479a0ff920b07db6b434d0571f34bfc2c6a9f94187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
